- import_playbook: create_reverse_proxy_vm.yml
- import_playbook: create_webserver_vm.yml

- hosts: localhost
  name: Refresh Inventory to Include New VMs
  tasks:
    - name: Refresh Dynamic Inventory
      meta: refresh_inventory
- import_playbook: init_managed_nodes.yaml
