- hosts: reverse_proxy
  name: Initialize Reverse Proxy
  become: true
  tasks:
    - name: "Install HAProxy"
      package:
        name: haproxy
    - name: Transfer HAProxy Config to Reverse Proxy
      template:
        dest: "/etc/haproxy/haproxy.cfg"
        src: "/home/azureuser/dev/IaC_Ansible_Assignment/haproxy.cfg"
    - name: Start HAProxy Service
      service:
        state: restarted
        name: haproxy

- hosts: web_server
  name: Initialize Web Server
  become: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: install python
      ansible.builtin.apt:
        name: python3
        state: latest
    - name: install firewalld
      ansible.builtin.apt:
        name: firewalld
        state: latest
    - name: apache2 installed
      ansible.builtin.apt:
        name: apache2
        state: latest
    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          Web Server Reached          
    - name: apache2 service enabled
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
